
(load "rc-files/installations/yasnippet-rc.el")
(load "rc-files/installations/auctex-rc.el")
(load "rc-files/installations/magic-latex-buffer-rc.el")
(load "rc-files/installations/reftex-rc.el")
(load "rc-files/installations/kpm-list-rc.el")
(load "rc-files/installations/helm-rc.el")
(load "rc-files/installations/iswitchb-rc.el")
(load "rc-files/installations/ido-mode-rc.el")
(load "rc-files/installations/undo-tree-rc.el")
(load "rc-files/installations/desktop-registry-rc.el")
(load "rc-files/installations/dired-mode-rc.el")
(load "rc-files/installations/paredit-rc.el")
(load "rc-files/installations/git-rc.el")
(load "rc-files/installations/autocomplete-rc.el")
(load "rc-files/installations/latex-mode-rc.el")
(load "rc-files/installations/flycheck-rc.el")
